import * as THREE from 'three';
import './style-fixed.css';

const app=document.getElementById('app');
app.innerHTML=`<div id="hud"><div class="panel brand">AHMAD<span>X</span> • TACTICAL COURTYARD</div><div class="panel score">SCORE <b id="score">0</b> • WAVE <b id="wave">1</b></div><div class="panel help">WASD move • Mouse look • Click fire • 1–6 weapons • R reload • H heal</div><div id="msg"></div><div class="panel health">HEALTH <b id="hp">100</b><div class="bar"><div id="hpFill"></div></div><div class="heal">Healing drink: <b id="heals">3</b> • H</div></div><div class="panel weapon"><div class="eyebrow">CURRENT WEAPON</div><div id="weaponName">Glock 17</div><div id="ammo">17 <small>/ 85</small></div></div><div id="slots"></div><div id="cross"></div><div id="damage"></div></div><div id="menu" class="menu"><div class="card"><div class="logo">AHMAD<span>X</span></div><div class="sub">Hosted 3D tactical FPS. Click Start, then click inside the game if your mouse is not captured. Move with WASD, sprint with Shift, shoot with left click, reload with R, heal with H, and switch weapons with 1–6.</div><div class="grid"><div class="key"><b>W A S D</b> — move</div><div class="key"><b>Mouse</b> — look / aim</div><div class="key"><b>Left click</b> — fire</div><div class="key"><b>1–6</b> — knife to bazooka</div><div class="key"><b>R</b> — reload</div><div class="key"><b>H</b> — healing drink</div></div><button id="startBtn">START AHMADX</button></div></div>`;

const $=id=>document.getElementById(id);
const scene=new THREE.Scene();scene.background=new THREE.Color(0xa4b8ca);scene.fog=new THREE.Fog(0xa4b8ca,35,115);
const camera=new THREE.PerspectiveCamera(72,innerWidth/innerHeight,.05,180);camera.position.set(0,1.7,18);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;app.prepend(renderer.domElement);
scene.add(new THREE.HemisphereLight(0xe0efff,0x5c4636,2.1));const sun=new THREE.DirectionalLight(0xffddb8,3.4);sun.position.set(-14,24,10);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const mat=(c,r=.75,m=0)=>new THREE.MeshStandardMaterial({color:c,roughness:r,metalness:m});
function box(x,y,z,w,h,d,c,r=.78){const o=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),mat(c,r));o.position.set(x,y+h/2,z);o.castShadow=o.receiveShadow=true;scene.add(o);return o}
const floor=new THREE.Mesh(new THREE.PlaneGeometry(70,80),mat(0xb59a7e,.92));floor.rotation.x=-Math.PI/2;floor.receiveShadow=true;floor.position.z=-8;scene.add(floor);const grid=new THREE.GridHelper(70,35,0x705b47,0x967e67);grid.position.set(0,.01,-8);scene.add(grid);
box(0,0,-30,48,10,2,0x9b5f45);box(-25,0,-7,2,10,48,0xc9a682);box(25,0,-7,2,10,48,0xc9a682);box(-14,0,-10,5,3.2,4,0x75543e);box(13,0,-12,6,2.7,4,0x76553f);box(-6,0,0,4,2.5,3,0x8a674c);box(8,0,3,5,2.8,3,0x8a674c);
for(let i=0;i<8;i++)box(-21+i*6,0,-27,1.1,8,1.1,0xd7b08c,.62);box(-5.6,0,-28,3.4,8,2.2,0xd9ad86);box(5.6,0,-28,3.4,8,2.2,0xd9ad86);box(0,6,-28,8,2,2.2,0xd9ad86);
for(const [x,z,s] of [[-10,-4,10],[2,-9,12],[12,-2,8]]){const p=new THREE.Mesh(new THREE.PlaneGeometry(s,5),new THREE.MeshStandardMaterial({color:0xb7435e,side:THREE.DoubleSide,roughness:.8}));p.rotation.x=Math.PI/2+.13;p.position.set(x,7.5,z);p.castShadow=true;scene.add(p)}

const weapons=[{name:'Combat Knife',mag:999,ammo:999,res:999,damage:70,rate:420,range:2.2,type:'melee'},{name:'Glock 17',mag:17,ammo:17,res:85,damage:34,rate:220,range:90,type:'gun'},{name:'MX-4 Rifle',mag:30,ammo:30,res:150,damage:25,rate:95,range:120,type:'gun'},{name:'Pump Shotgun',mag:8,ammo:8,res:40,damage:17,rate:650,range:40,type:'shotgun'},{name:'SR-1 Sniper',mag:5,ammo:5,res:25,damage:125,rate:1050,range:160,type:'gun'},{name:'BX-9 Bazooka',mag:1,ammo:1,res:6,damage:175,rate:1600,range:130,type:'rocket'}];
let wi=1,score=0,wave=1,hp=100,heals=3,lastShot=0,reloading=false,started=false,locked=false,yaw=0,pitch=0;const keys={},enemies=[],rockets=[];
weapons.forEach((w,i)=>{const s=document.createElement('div');s.id='slot'+i;s.className='slot';s.textContent=(i+1)+' '+w.name;$('slots').appendChild(s)});
function hud(){const w=weapons[wi];$('weaponName').textContent=w.name;$('ammo').innerHTML=(w.type==='melee'?'∞':w.ammo)+` <small>/ ${w.type==='melee'?'∞':w.res}</small>`;$('score').textContent=score;$('wave').textContent=wave;$('hp').textContent=Math.ceil(hp);$('hpFill').style.width=Math.max(0,hp)+'%';$('heals').textContent=heals;weapons.forEach((_,i)=>$('slot'+i).className='slot'+(i===wi?' active':''))}hud();
function say(t,ms=850){$('msg').textContent=t;setTimeout(()=>{if($('msg').textContent===t)$('msg').textContent=''},ms)}

const weaponGroup=new THREE.Group();camera.add(weaponGroup);scene.add(camera);weaponGroup.scale.setScalar(.72);weaponGroup.position.set(-.02,-.02,-.05);
function part(g,geom,c,pos,rot=[0,0,0],metal=.25){const m=new THREE.Mesh(geom,mat(c,.36,metal));m.position.set(...pos);m.rotation.set(...rot);m.castShadow=true;g.add(m);return m}
function rebuildWeapon(){weaponGroup.clear();const w=weapons[wi];if(w.type==='melee'){part(weaponGroup,new THREE.BoxGeometry(.08,.08,.48),0x5a3823,[.34,-.28,-.72],[.08,0,-.2]);part(weaponGroup,new THREE.ConeGeometry(.05,.58,4),0xd3dbe2,[.34,-.08,-.98],[Math.PI/2,0,-.2],.7);return}if(w.name==='Glock 17'){part(weaponGroup,new THREE.BoxGeometry(.24,.14,.58),0x15191d,[.30,-.22,-.80]);part(weaponGroup,new THREE.BoxGeometry(.14,.30,.18),0x202832,[.27,-.39,-.66],[.13,0,0]);part(weaponGroup,new THREE.BoxGeometry(.055,.05,.34),0x080b0e,[.30,-.22,-1.20],[0,0,0],.8)}else if(w.name==='MX-4 Rifle'){part(weaponGroup,new THREE.BoxGeometry(.26,.17,1.05),0x151a20,[.30,-.22,-1.00]);part(weaponGroup,new THREE.BoxGeometry(.14,.36,.20),0x1c242c,[.27,-.40,-.82],[.1,0,0]);part(weaponGroup,new THREE.BoxGeometry(.055,.055,.72),0x080b0e,[.30,-.22,-1.88],[0,0,0],.8)}else if(w.name==='Pump Shotgun'){part(weaponGroup,new THREE.BoxGeometry(.24,.16,1.0),0x14191e,[.30,-.23,-.98]);part(weaponGroup,new THREE.BoxGeometry(.28,.14,.30),0x664b39,[.30,-.23,-1.28]);part(weaponGroup,new THREE.BoxGeometry(.05,.05,.80),0x080b0e,[.30,-.23,-1.82],[0,0,0],.8)}else if(w.name==='SR-1 Sniper'){part(weaponGroup,new THREE.BoxGeometry(.23,.15,1.1),0x12171d,[.30,-.23,-1.0]);part(weaponGroup,new THREE.CylinderGeometry(.06,.06,.48,16),0x090c10,[.30,-.13,-.90],[Math.PI/2,0,0],.8);part(weaponGroup,new THREE.BoxGeometry(.045,.045,.90),0x080b0e,[.30,-.23,-2.0],[0,0,0],.8)}else{part(weaponGroup,new THREE.CylinderGeometry(.16,.16,1.18,24),0x2f3a43,[.30,-.22,-1.05],[Math.PI/2,0,0],.45);part(weaponGroup,new THREE.BoxGeometry(.12,.30,.14),0x1a232c,[.30,-.39,-.84],[.1,0,0])}}rebuildWeapon();

function enemy(x,z){const g=new THREE.Group(),skin=mat(0xc79572,.9),cloth=mat(Math.random()>.5?0x596f81:0x704d5d,.72),dark=mat(0x1a222b,.6,.12);const head=new THREE.Mesh(new THREE.SphereGeometry(.28,20,16),skin);head.position.y=1.72;g.add(head);const torso=new THREE.Mesh(new THREE.CapsuleGeometry(.34,.74,6,14),cloth);torso.position.y=1.08;g.add(torso);for(const s of [-1,1]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.12,.72,5,10),dark);leg.position.set(.18*s,.30,0);g.add(leg);const arm=new THREE.Mesh(new THREE.CapsuleGeometry(.09,.58,5,10),skin);arm.position.set(.40*s,1.13,-.05);arm.rotation.z=.18*s;g.add(arm)}const gun=new THREE.Mesh(new THREE.BoxGeometry(.50,.10,.12),dark);gun.position.set(0,1.08,-.36);g.add(gun);g.position.set(x,0,z);g.userData={hp:100,lastAttack:0,speed:1.0+Math.random()*.35,dead:false};g.traverse(o=>{if(o.isMesh){o.castShadow=true;o.receiveShadow=true;o.userData.enemy=g}});scene.add(g);enemies.push(g)}
function spawnWave(){while(enemies.length){scene.remove(enemies.pop())}const n=Math.min(5+wave,10);for(let i=0;i<n;i++){const lane=(i%5)-2;enemy(lane*4+(Math.random()-.5)*1.5,-10-Math.floor(i/5)*7-Math.random()*4)}say('WAVE '+wave,1200)}spawnWave();
const ray=new THREE.Raycaster();
function aimDir(spread=0){const d=new THREE.Vector3(0,0,-1).applyEuler(new THREE.Euler(pitch,yaw,0,'YXZ'));d.x+=(Math.random()-.5)*spread;d.y+=(Math.random()-.5)*spread;d.z+=(Math.random()-.5)*spread;return d.normalize()}
function hitScan(dmg,range,spread){ray.set(camera.position,aimDir(spread));ray.far=range;const meshes=[];enemies.forEach(e=>e.traverse(o=>o.isMesh&&meshes.push(o)));const h=ray.intersectObjects(meshes,false)[0];if(h&&h.object.userData.enemy){const e=h.object.userData.enemy;e.userData.hp-=dmg*(h.object.geometry.type==='SphereGeometry'?1.65:1);if(e.userData.hp<=0&&!e.userData.dead){e.userData.dead=true;score+=100;scene.remove(e);enemies.splice(enemies.indexOf(e),1);if(!enemies.length){wave++;setTimeout(spawnWave,650)}hud()}}}
function fire(){if(!started||reloading)return;const w=weapons[wi],now=performance.now();if(now-lastShot<w.rate)return;lastShot=now;if(w.type!=='melee'&&w.ammo<=0){reload();return}if(w.type!=='melee')w.ammo--;weaponGroup.position.z=.03;if(w.type==='rocket'){const dir=aimDir(.004),m=new THREE.Mesh(new THREE.SphereGeometry(.09,12,8),new THREE.MeshBasicMaterial({color:0xffa21a}));m.position.copy(camera.position).add(dir.clone().multiplyScalar(.8));scene.add(m);rockets.push({m,v:dir.multiplyScalar(26),life:4})}else if(w.type==='shotgun'){for(let i=0;i<8;i++)hitScan(w.damage,w.range,.10)}else hitScan(w.damage,w.range,w.type==='melee'?0:.010);hud()}
function reload(){const w=weapons[wi];if(reloading||w.type==='melee'||w.ammo===w.mag||w.res<=0)return;reloading=true;say('RELOADING...');setTimeout(()=>{const n=Math.min(w.mag-w.ammo,w.res);w.ammo+=n;w.res-=n;reloading=false;hud()},900)}
function heal(){if(heals<=0||hp>=100)return;heals--;hp=Math.min(100,hp+45);say('HEALING +45');hud()}
function hurt(v){hp=Math.max(0,hp-v);$('damage').style.background='rgba(255,0,0,.22)';setTimeout(()=>$('damage').style.background='rgba(255,0,0,0)',80);if(hp<=0){hp=100;heals=3;camera.position.set(0,1.7,18);yaw=0;pitch=0;say('RESPAWNED')}hud()}

$('startBtn').addEventListener('click',()=>{started=true;$('menu').style.display='none';yaw=0;pitch=0;camera.rotation.set(0,0,0);say('MISSION START');try{renderer.domElement.requestPointerLock?.()}catch(_){}});
renderer.domElement.addEventListener('click',()=>{if(started&&!locked){try{renderer.domElement.requestPointerLock?.()}catch(_){}}});document.addEventListener('pointerlockchange',()=>locked=document.pointerLockElement===renderer.domElement);
document.addEventListener('mousemove',e=>{if(!started||!locked)return;yaw-=e.movementX*.002;pitch-=e.movementY*.002;pitch=Math.max(-.72,Math.min(.72,pitch))});
document.addEventListener('mousedown',e=>{if(e.button===0&&started)fire()});document.addEventListener('keydown',e=>{keys[e.code]=true;if(e.code==='KeyR')reload();if(e.code==='KeyH')heal();if(/^Digit[1-6]$/.test(e.code)){wi=+e.code.slice(-1)-1;reloading=false;rebuildWeapon();hud()}});document.addEventListener('keyup',e=>keys[e.code]=false);
let prev=performance.now();function loop(t){requestAnimationFrame(loop);const dt=Math.min(.033,(t-prev)/1000);prev=t;if(started){const f=new THREE.Vector3(Math.sin(yaw),0,-Math.cos(yaw)),r=new THREE.Vector3(Math.cos(yaw),0,Math.sin(yaw)),m=new THREE.Vector3();if(keys.KeyW)m.add(f);if(keys.KeyS)m.sub(f);if(keys.KeyD)m.add(r);if(keys.KeyA)m.sub(r);if(m.lengthSq())m.normalize().multiplyScalar((keys.ShiftLeft?8:5.3)*dt);camera.position.add(m);camera.position.x=Math.max(-22,Math.min(22,camera.position.x));camera.position.z=Math.max(-24,Math.min(20,camera.position.z));camera.position.y=1.7;camera.rotation.set(pitch,yaw,0,'YXZ');weaponGroup.position.lerp(new THREE.Vector3(-.02,-.02,-.05),.22);for(const e of [...enemies]){const d=camera.position.clone().sub(e.position);d.y=0;const dist=d.length();if(dist>4.5){e.position.addScaledVector(d.normalize(),e.userData.speed*dt);e.lookAt(camera.position.x,e.position.y,camera.position.z)}if(dist<14&&t-e.userData.lastAttack>1100+Math.random()*500){e.userData.lastAttack=t;if(Math.random()<.5)hurt(3+Math.random()*4)}}for(let i=rockets.length-1;i>=0;i--){const p=rockets[i];p.m.position.addScaledVector(p.v,dt);p.life-=dt;let boom=p.life<=0;for(const e of enemies)if(p.m.position.distanceTo(e.position)<1.1)boom=true;if(boom){for(const e of [...enemies]){const d=e.position.distanceTo(p.m.position);if(d<6){e.userData.hp-=Math.max(30,175*(1-d/6));if(e.userData.hp<=0){score+=100;scene.remove(e);enemies.splice(enemies.indexOf(e),1)}}}scene.remove(p.m);rockets.splice(i,1);if(!enemies.length){wave++;setTimeout(spawnWave,650)}hud()}}}renderer.render(scene,camera)}requestAnimationFrame(loop);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});
